apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-simpleBootstrap-setting
spec:
  forms:
    - group: general
      label: 基本设置
      formSchema:
        - $formkit: color
          name: scrollbar_background_color
          label: 滚动条颜色
          value: '#6c757d'
          placeholder: '滚动条颜色'
        - $formkit: color
          name: link_color
          label: 链接颜色
          value: '#007bff'
          placeholder: '链接颜色'
        - $formkit: color
          name: hover_color
          label: 鼠标滑过颜色
          value: '#dc3545'
          placeholder: '鼠标滑过颜色'
        - $formkit: color
          name: progress_color
          label: 阅读进度条颜色
          value: '#dc3545'
          placeholder: '阅读进度条颜色'
        - $formkit: radio
          name: open_rss
          label: 是否启用RSS
          data-type: bool
          value: true
          options:
            - value: true
              label: 启用
            - value: false
              label: 关闭
        - $formkit: radio
          name: open_read_progress
          label: 是否使用阅读进度条
          data-type: bool
          value: true
          options:
            - value: true
              label: 显示
            - value: false
              label: 关闭
        - $formkit: radio
          name: link_on_blank_page
          label: 启用新标签页打开链接
          data-type: bool
          value: true
          options:
            - value: true
              label: 启用
            - value: false
              label: 关闭
        - $formkit: radio
          name: open_share
          label: 是否启用分享
          data-type: bool
          value: true
          options:
            - value: true
              label: 启用
            - value: false
              label: 关闭
        - $formkit: text
          name: twitter_account_share
          label: 转发时@推特账号
          value: ''
          placeholder: '转发时@推特账号'
        - $formkit: textarea
          name: journals_description
          label: 日志界面的描述信息
          value: ''
          placeholder: '日志界面的描述信息'
    - group: user_info
      label: 用户信息
      formSchema:
        - $formkit: text
          name: avatar
          label: 头像地址
        - $formkit: text
          name: nickname
          label: 昵称
        - $formkit: text
          name: user_location
          label: 位置信息
          value: '北京 海淀'
          placeholder: '住址'
        - $formkit: text
          name: github_url
          label: Github地址
          value: ''
          placeholder: 'Github地址'
        - $formkit: number
          name: qq_number
          label: QQ账号(需开通 https://shang.qq.com/v3/widget.html)
          value: ''
          placeholder: 'QQ账号'
        - $formkit: text
          name: weibo_url
          label: 微博链接
          value: ''
          placeholder: '微博链接'
        - $formkit: text
          name: twitter_account
          label: 推特账号
          value: ''
          placeholder: '推特账号'
        - $formkit: email
          name: email_address
          label: 邮箱地址
          value: ''
          placeholder: '邮箱地址'
    - group: code
      label: 代码设置
      formSchema:
        - $formkit: radio
          name: line_number
          label: 是否显示行号
          data-type: bool
          value: true
          options:
            - value: true
              label: 显示
            - value: false
              label: 关闭
        - $formkit: radio
          name: code_copy
          label: 是否启用代码复制
          data-type: bool
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: code_type
          label: 是否在代码右上角显示代码类型
          data-type: bool
          value: true
          options:
            - value: true
              label: 显示
            - value: false
              label: 关闭
        - $formkit: radio
          name: mobile_catalog
          label: 是否在手机上启用目录功能
          data-type: bool
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: text
          name: code_css_url
          label: 代码样式地址
          value: 'https://cdn.staticfile.org/highlight.js/9.18.1/styles/github.min.css'
          placeholder: '代码样式地址'
        - $formkit: text
          name: code_font_family
          label: 代码字体(注意引号)
          value: '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace'
          placeholder: '代码字体'