apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-simple-bootstrap-next
spec:
  displayName: Simple Bootstrap
  author:
    name: CY
    website: https://halo.cyblogs.top
  description: 使用Bootstrap构建的简洁主题
  logo: https://halo.run/logo
  website: https://halo.cyblogs.top
  repo: https://github.com/shuTwT/halo-theme-simpleBootstrap-next
  settingName: theme-simple-bootstrap-setting
  configMapName: theme-simple-bootstrap-configMap
  version: "2.0.2"
  require: ">=2.8.0"
